version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: pgsql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.27.0.2
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php-development:8.2
    container_name: php
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      .env
    volumes:
      - ./backend:/var/www/
    depends_on:
      - postgresql
    networks:
      backend:
        ipv4_address: 172.27.0.3
networks:
  backend:
    external: true
    name: url-shortener-network